# Generated by Django 5.2 on 2025-04-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.ImageField(blank=True, upload_to='pet_images/'),
        ),
    ]
